/*-------------------------Crear un tablespace------------------------------*/
create tablespace TBS_PROYECTO datafile
'C:\Users\Mau\Music\Lenguaje-BD\oradata\ORCL\proyecto1.dbf ' size 20M default storage (initial
1m next 1m pctincrease 0);

/*-----------------------MODIFCAR LA SESSION---------------------------------*/
alter session set "_ORACLE_SCRIPT"=true;
/*----------------------Habilitar outputs------------------------------------*/
SET SERVEROUTPUT ON;

/*------------Asigno a mi usuario el tablespack creado----------------------*/
alter user adm_proyecto quota unlimited on TBS_PROYECTO;

/*creacion de users y asignarles el tablespace TBS_PROYECTO*/
create user adm_db identified by "123456" default tablespace TBS_PROYECTO;
create user adm_cliente identified by "123456" default tablespace TBS_PROYECTO;
create user adm_membresias identified by "123456" default tablespace TBS_PROYECTO;


/*---------------Creacion de rols---------------------------------------*/
create role rol_adm_db;
create role rol_adm_cliente;
create role rol_adm_membresias;

/*----------------------DAR permisos especificos a un rol--------------*/
/*GRANT SELECT,INSERT,UPDATE,DELETE ON CLIENTE TO rol_adm_cliente;*/

/*Dar permisos a users, en este caso a adm_db*/
/*grant create session to adm_db;
grant connect to adm_db;
grant dba to adm_db;*/

/*---------------------CREAR TABLAS--------------------------------*/

create table CLIENTE
(
    ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (50) NOT NULL,
    APELLIDO VARCHAR (50) NOT NULL,
    FECHAINGRESO DATE NOT NULL,
    MENSUALIDAD INT NOT NULL
);

create table AUD_CLIENTE
(
    CONSECUTIVO NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (50) NOT NULL,
    APELLIDO VARCHAR (50) NOT NULL,
    FECHAINGRESO DATE NOT NULL,
    MENSUALIDAD INT NOT NULL,
    
    ACCION VARCHAR(100) NOT NULL,
    FECHA_MOV TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_MOV VARCHAR2(100) DEFAULT USER
);


create table MEMBRESIAS
(
    ID_MEMBRESIA INT NOT NULL PRIMARY KEY,
    TIPO VARCHAR (50) NOT NULL,
    ESTADO VARCHAR (50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_EXPIRACION DATE NOT NULL,
    ID_CLIENTE INT NOT NULL
);

create table EMPLEADO(
    ID_EMPLEADO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (20) NOT NULL,
    APELLIDO VARCHAR (25) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    ESTADO VARCHAR(45) NOT NULL,
    SALARIO INT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO INT NOT NULL,
    PUESTO VARCHAR(50) NOT NULL
);

create table AUD_EMPLEADO(

    CONSECUTIVO NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    ID_EMPLEADO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (20) NOT NULL,
    APELLIDO VARCHAR (25) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    ESTADO VARCHAR(45) NOT NULL,
    SALARIO INT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO INT NOT NULL,
    PUESTO VARCHAR(50) NOT NULL,
    
    ACCION VARCHAR(100) NOT NULL,
    FECHA_MOV TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_MOV VARCHAR2(100) DEFAULT USER
);

create table CLASES(
    ID_CLASE INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR (50) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL,
    ESPACIOS INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    ID_HORARIO INT NOT NULL
);

create table AUD_CLASES(

    CONSECUTIVO NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    ID_CLASE INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR (50) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL,
    ESPACIOS INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    ID_HORARIO INT NOT NULL,
    
    ACCION VARCHAR(100) NOT NULL,
    FECHA_MOV TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_MOV VARCHAR2(100) DEFAULT USER
);    

create table RESERVAS(
    ID_RESERVA INT NOT NULL PRIMARY KEY,
    ESTADO VARCHAR(45) NOT NULL,
    ID_CLASE INT NOT NULL,
    ID_CLIENTE INT NOT NULL
);

create table AUD_RESERVAS(
    CONSECUTIVO NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    ID_RESERVA INT NOT NULL PRIMARY KEY,
    ESTADO VARCHAR(45) NOT NULL,
    ID_CLASE INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    
    ACCION VARCHAR(100) NOT NULL,
    FECHA_MOV TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_MOV VARCHAR2(100) DEFAULT USER
);

create table HORARIO(
    ID_HORARIO INT NOT NULL PRIMARY KEY,
    DIA VARCHAR (20) NOT NULL,
    HORA_INICIO TIMESTAMP  NOT NULL,
    HORA_FIN TIMESTAMP  NOT NULL
);

create table FACTURA(
    ID_FACTURA INT NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    MONTO INT NOT NULL,
    FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR (100) NOT NULL
);

create table AUD_FACTURA(
    CONSECUTIVO NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    ID_FACTURA INT NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    MONTO INT NOT NULL,
    FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR (100) NOT NULL,
    
    ACCION VARCHAR(100) NOT NULL,
    FECHA_MOV TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_MOV VARCHAR2(100) DEFAULT USER
);


/*------------Agregar FK de tablas--------------------------------------*/

/* FK para tabla MEMBRESIAS*/
alter table "ADM_PROYECTO"."MEMBRESIAS" 
add constraint FK_ID_CLIENTE 
foreign key("ID_CLIENTE") 
references "CLIENTE"("ID_CLIENTE");

/* FK para tabla CLASES*/
alter table "ADM_PROYECTO"."CLASES" 
add constraint FK_ID_EMPLEADO 
foreign key("ID_EMPLEADO") 
references "EMPLEADO"("ID_EMPLEADO");

alter table "ADM_PROYECTO"."CLASES" 
add constraint FK_ID_HORARIO 
foreign key("ID_HORARIO") 
references "HORARIO"("ID_HORARIO");

/* FK para tabla RESERVAS*/
alter table "ADM_PROYECTO"."RESERVAS" 
add constraint FK_ID_CLASE 
foreign key("ID_CLASE") 
references "CLASES"("ID_CLASE");

alter table "ADM_PROYECTO"."RESERVAS" 
add constraint FK_ID_RCLIENTE 
foreign key("ID_CLIENTE") 
references "CLIENTE"("ID_CLIENTE");

/* FK para tabla FACTURA*/
alter table "ADM_PROYECTO"."FACTURA" 
add constraint FK_ID_FCLIENTE 
foreign key("ID_FACTURA") 
references "FACTURA"("ID_FACTURA");


/*-------------------Inserts------------------------------*/
insert into CLIENTE values(1,'Fabiola','Rodriguez','09/10/2023',1);
insert into CLIENTE values(2,'Carlos','Rodriguez','15/03/2023',2);
insert into CLIENTE values(3,'Lucia','Vargas','03/09/2023',1);

insert into MEMBRESIAS values(1,'VIP','Activo','11/11/2023','11/12/2023',1);
insert into MEMBRESIAS values(2,'STANDARD','Activo','15/10/2023','15/11/2023',2);
insert into MEMBRESIAS values(3,'VIP','Activo','03/11/2023','03/12/2023',3);

insert into HORARIO values(1,'Lunes', TO_TIMESTAMP('14:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00', 'HH24:MI:SS'));
insert into HORARIO values(2,'Martes', TO_TIMESTAMP('16:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00', 'HH24:MI:SS'));
insert into HORARIO values(3,'Martes', TO_TIMESTAMP('18:00', 'HH24:MI:SS'), TO_TIMESTAMP('20:00', 'HH24:MI:SS'));

insert into EMPLEADO values(1,'Felipe','Castro','01/10/2023', 'Activo', 400000, 'fcatro@gmail.com', 78125878, 'Instructor');
insert into EMPLEADO values(2,'Alonso','Rojas','11/02/2023', 'Activo', 250000, 'arojas@gmail.com', 45715684, 'Secretario');
insert into EMPLEADO values(3,'Kristel','Lopez','05/03/2023', 'Activo', 400000, 'klopez@gmail.com', 78965812, 'Instructor');

insert into CLASES values(1,'Funcional','Activa',15,1,1);
insert into CLASES values(2,'Boxing','Activa',15,3,2);
insert into CLASES values(3,'Yoga','Activa',10,3,3);

insert into RESERVAS values(1, 'Confirmada', 2, 1);
insert into RESERVAS values(2, 'Pendiente', 1, 3);
insert into RESERVAS values(3, 'Confirmada', 3, 2);

insert into FACTURA values(1, 1, 50000, TO_DATE('2023-10-30', 'YYYY-MM-DD'), 'Pago de membresia');
insert into FACTURA values(2, 2, 30000, TO_DATE('2023-11-05', 'YYYY-MM-DD'), 'Pago de clases de yoga');
insert into FACTURA values(3, 3, 75000, TO_DATE('2023-11-10', 'YYYY-MM-DD'), 'Pago de entrenamiento personal');

/*-------------------------PROCEDIMIENTOS ALMACENADOS-------------------*/

/*---------SP para insertar clientes-------------------*/
--1
CREATE OR REPLACE PROCEDURE INSERT_CLIENTE(
	   c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
	   c_NOMBRE IN CLIENTE.NOMBRE%TYPE,
	   c_APELLIDO IN CLIENTE.APELLIDO %TYPE,
	   c_FECHAINGRESO IN CLIENTE.FECHAINGRESO%TYPE,
	   c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE)
AS
BEGIN

  INSERT INTO CLIENTE ("ID_CLIENTE", "NOMBRE", "APELLIDO", "FECHAINGRESO","MENSUALIDAD") 
  VALUES (c_ID_CLIENTE, c_NOMBRE, c_APELLIDO, c_FECHAINGRESO, c_MENSUALIDAD);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro de ' || c_NOMBRE || ' ha sido insertado');

END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_CLIENTE(4,'Xinia','Lopez','09/10/2010',2);

---------------Trigger se dispara cuando un cliente es agregado--------------------- 1t--
CREATE OR REPLACE TRIGGER TGR_INSERT_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO AUD_CLIENTE (
        ID_CLIENTE,
        NOMBRE,
        APELLIDO,
        FECHAINGRESO,
        MENSUALIDAD,
        ACCION
    ) VALUES (
        :NEW.ID_CLIENTE,
        :NEW.NOMBRE,
        :NEW.APELLIDO,
        :NEW.FECHAINGRESO,
        :NEW.MENSUALIDAD,
        'INSERT'
    );
END;

--------------Probar Triggerr---------------------------------------
EXEC INSERT_CLIENTE(5,'Lupe','Rojas','09/10/2018',1);
EXEC INSERT_CLIENTE(6,'Gabriel','Valverde','09/10/2020',1);

/*---------SP para modificar la mensualidad de los clientes-------------------*/

CREATE OR REPLACE PROCEDURE UPDATE_CLIENTE(
	   c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
	   c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE)
AS
BEGIN

  UPDATE CLIENTE
    SET MENSUALIDAD = c_MENSUALIDAD
    WHERE ID_CLIENTE = c_ID_CLIENTE;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_CLIENTE(6,2);

-------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE UPDATE_CLIENTENOM(
	   c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
	   c_NOMBRE IN CLIENTE.NOMBRE%TYPE)
AS
BEGIN

  UPDATE CLIENTE
    SET NOMBRE = c_NOMBRE
    WHERE ID_CLIENTE = c_ID_CLIENTE;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_CLIENTENOM(1,'Mau');

/*---------SP para eliminar clientes-------------------*/
--3
CREATE OR REPLACE PROCEDURE DELETE_CLIENTE(
	   c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE)
AS
BEGIN

  DELETE FROM CLIENTE
    WHERE ID_CLIENTE = c_ID_CLIENTE;
  DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido eliminado');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_CLIENTE(6);

/*---------SP para insertar membresias-------------------*/
--4
CREATE OR REPLACE PROCEDURE INSERT_MEMBRESIA(
	   m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA%TYPE,
	   m_TIPO IN MEMBRESIAS.TIPO%TYPE,
	   m_ESTADO IN MEMBRESIAS.ESTADO%TYPE,
	   m_FECHA_INICIO IN MEMBRESIAS.FECHA_INICIO%TYPE,
	   m_FECHA_EXPIRACION IN MEMBRESIAS.FECHA_EXPIRACION%TYPE,
	   m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE)
IS
BEGIN

  INSERT INTO MEMBRESIAS("ID_MEMBRESIA", "TIPO", "ESTADO", "FECHA_INICIO","FECHA_EXPIRACION","ID_CLIENTE") 
  VALUES (m_ID_MEMBRESIA, m_TIPO, m_ESTADO, m_FECHA_INICIO, m_FECHA_EXPIRACION, m_ID_CLIENTE);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro de ' || m_ID_MEMBRESIA || ' ha sido insertado');

END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_MEMBRESIA(4,'Standard','Activo','10/11/2023','10/12/2023',4);

/*---------SP para modificar el estado de membresia segun el ID del cliente----*/
--5
CREATE OR REPLACE PROCEDURE UPDATE_MEMBRESIAS(
	   m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE,
	   m_ESTADO IN MEMBRESIAS.ESTADO%TYPE)
AS
BEGIN

  UPDATE MEMBRESIAS
    SET ESTADO = m_ESTADO
    WHERE ID_CLIENTE = m_ID_CLIENTE;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('EL estado de la membresia del cliente con ID: ' || m_ID_CLIENTE || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_MEMBRESIAS(3,'Inactio');

/*---------SP para eliminar membresias-------------------*/
--6
CREATE OR REPLACE PROCEDURE DELETE_MEMBRESIA(
	   m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA %TYPE)
AS
BEGIN

  DELETE FROM MEMBRESIAS
    WHERE ID_MEMBRESIA = m_ID_MEMBRESIA;
  DBMS_OUTPUT.PUT_LINE('El registro de la membresia con ID: ' || m_ID_MEMBRESIA || ' ha sido eliminada');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_MEMBRESIA(4);
--------------------------------------------------------------------------
--7
CREATE OR REPLACE PROCEDURE INSERT_RESERVA(
    r_ID_RESERVA IN INT,
    r_ESTADO_RESERVA IN VARCHAR2,
    r_ID_CLASE IN INT,
    r_ID_CLIENTE IN INT
) AS
    c_ESPACIOS_DISPONIBLES INT;
BEGIN
    --Cuantos espacios hay disponibles en la clase
    SELECT ESPACIOS INTO c_ESPACIOS_DISPONIBLES
    FROM CLASES
    WHERE ID_CLASE = r_ID_CLASE;
    IF c_ESPACIOS_DISPONIBLES > 0 THEN
        --Si hay espacios, se inserta la reserva
        INSERT INTO RESERVAS (
            ID_RESERVA,
            ESTADO,
            ID_CLASE,
            ID_CLIENTE
        ) VALUES (
            r_ID_RESERVA,
            r_ESTADO_RESERVA,
            r_ID_CLASE,
            r_ID_CLIENTE
        );

        --Se actualiza la tabla Clases y se elimina un espacio
        UPDATE CLASES
        SET ESPACIOS = c_ESPACIOS_DISPONIBLES - 1
        WHERE ID_CLASE = r_ID_CLASE;
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('La resrva fue creada y se reducio un espacio en la clase ' || r_ID_CLASE);
    ELSE
        -- Si no hay espacio
        DBMS_OUTPUT.PUT_LINE('No hay suficiente espacio para esta clase.');
    END IF;
END INSERT_RESERVA;

-------------------------------------------------------------------------
EXEC INSERT_RESERVA(4,'Activa',3,3);

/*---------SP para modificar el estado de la reserva de los clientes-------------------*/
--8
CREATE OR REPLACE PROCEDURE UPDATE_RESERVA(
	   r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE,
	   r_ESTADO IN RESERVAS.ESTADO%TYPE)
AS
BEGIN

  UPDATE RESERVAS
    SET ESTADO = r_ESTADO
    WHERE ID_RESERVA = r_ID_RESERVA;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro del estado con ID: ' || r_ID_RESERVA || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_RESERVA(1,'Pendiente');

/*---------SP para eliminar reservas-------------------*/
--9
CREATE OR REPLACE PROCEDURE DELETE_RESERVAS(
	   r_ID_RESERVA IN RESERVAS.ID_RESERVA %TYPE)
AS
BEGIN

  DELETE FROM RESERVAS
    WHERE ID_RESERVA = r_ID_RESERVA;
  DBMS_OUTPUT.PUT_LINE('La reserva con ID: ' || r_ID_RESERVA || ' ha sido eliminada');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_RESERVAS(4);

/*---------------TRIGGER se dispara cuando una reserva es cancelada------------2t---*/
CREATE OR REPLACE TRIGGER TGR_DELETE_RESERVA
BEFORE DELETE ON RESERVAS
FOR EACH ROW
BEGIN
    INSERT INTO AUD_RESERVAS(
        ID_RESERVA,
        ESTADO,
        ID_CLASE,
        ID_CLIENTE,
        ACCION
    ) VALUES (
        :OLD.ID_RESERVA,
        :OLD.ESTADO,
        :OLD.ID_CLASE,
        :OLD.ID_CLIENTE,
        'DELETE'
    );
END;

------------Comprobar si funciona-----------------------------
EXEC DELETE_RESERVAS(3);

--------------CRUD de Horarios-------------------------------------
--10
CREATE OR REPLACE PROCEDURE INSERT_HORARIO(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_DIA IN HORARIO.DIA%TYPE,
    h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE,
    h_HORA_FIN IN HORARIO.HORA_FIN%TYPE)
AS
BEGIN
    INSERT INTO HORARIO (ID_HORARIO, DIA, HORA_INICIO, HORA_FIN)
    VALUES (h_ID_HORARIO, h_DIA, h_HORA_INICIO, h_HORA_FIN);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El horario con ID: ' || h_ID_HORARIO || ' ha sido insertado.');
END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_HORARIO(4,'Miercoles', TO_TIMESTAMP('18:00', 'HH24:MI:SS'), TO_TIMESTAMP('20:00', 'HH24:MI:SS'));



/*---------SP para modificar el dia del horario-------------------*/
--11
CREATE OR REPLACE PROCEDURE UPDATE_HORARIO(
	   h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
	   h_DIA IN HORARIO.DIA%TYPE)
AS
BEGIN

  UPDATE HORARIO
    SET DIA = h_DIA
    WHERE ID_HORARIO = h_ID_HORARIO;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('El dia con el horario ID de: ' || h_ID_HORARIO || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_HORARIO(3,'Lunes');

/*---------SP para modificar la hora de inicio de un horario-------------------*/
--12
CREATE OR REPLACE PROCEDURE UPDATE_HORARIO_INICIO(
	   h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
	   h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE)
AS
BEGIN

  UPDATE HORARIO
    SET HORA_INICIO = h_HORA_INICIO
    WHERE ID_HORARIO = h_ID_HORARIO;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('La hora de inicio para el horario con ID: ' || h_ID_HORARIO || ' ha sido modificada a ' || h_HORA_INICIO);

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_HORARIO_INICIO(3,TO_TIMESTAMP('14:00', 'HH24:MI:SS'));

/*---------SP para modificar la hora de finalizacion de un horario-------------------*/
--13
CREATE OR REPLACE PROCEDURE UPDATE_HORARIO_FIN(
	   h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
	   h_HORA_FIN IN HORARIO.HORA_FIN%TYPE)
AS
BEGIN

  UPDATE HORARIO
    SET HORA_FIN = h_HORA_FIN
    WHERE ID_HORARIO = h_ID_HORARIO;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('La hora de finalizacion para el horario con ID: ' || h_ID_HORARIO || ' ha sido modificada a ' || h_HORA_FIN);

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_HORARIO_FIN(3,TO_TIMESTAMP('18:00', 'HH24:MI:SS'));

/*---------SP para eliminar horarios-------------------*/
--14
CREATE OR REPLACE PROCEDURE DELETE_HORARIO(
	   h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE)
AS
BEGIN

  DELETE FROM HORARIO
    WHERE ID_HORARIO = h_ID_HORARIO;
  DBMS_OUTPUT.PUT_LINE('El horario con ID: ' || h_ID_HORARIO || ' ha sido eliminado');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_HORARIO(4);


----------------------CRUD para facturas------------------------------
--15
CREATE OR REPLACE PROCEDURE INSERT_FACTURA(
    f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
    f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE,
    f_MONTO IN FACTURA.MONTO%TYPE,
    f_FECHA IN FACTURA.FECHA%TYPE,
    f_DESCRIPCION IN FACTURA.DESCRIPCION%TYPE)
AS
BEGIN
    INSERT INTO FACTURA(ID_FACTURA, ID_CLIENTE, MONTO, FECHA, DESCRIPCION)
    VALUES (f_ID_FACTURA, f_ID_CLIENTE, f_MONTO, f_FECHA, f_DESCRIPCION);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro de factura con ID: ' || f_ID_FACTURA || ' ha sido insertado.');
END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_FACTURA(4, 2, 50000, TO_DATE('2023-10-30', 'YYYY-MM-DD'), 'Pago de membresia');

---------------Trigger se dispara cuando una reserva es agregada---------------------3t--
CREATE OR REPLACE TRIGGER TGR_INSERT_FACTURA
BEFORE INSERT ON FACTURA
FOR EACH ROW
BEGIN
    INSERT INTO AUD_FACTURA (
        ID_FACTURA,
        ID_CLIENTE,
        MONTO,
        FECHA,
        DESCRIPCION,
        ACCION
    ) VALUES (
        :NEW.ID_FACTURA,
        :NEW.ID_CLIENTE,
        :NEW.MONTO,
        :NEW.FECHA,
        :NEW.DESCRIPCION,
        'INSERT'
    );
END;

-----------------Probar trigger------------------------------
EXEC INSERT_FACTURA(5, 1, 50000, TO_DATE('2023-10-30', 'YYYY-MM-DD'), 'Pago de membresia');

/*---------SP para modificar el cliente en la tabla FACTURA-------------------*/
--16
CREATE OR REPLACE PROCEDURE UPDATE_FACTURA(
	   f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
	   f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE)
AS
BEGIN

  UPDATE FACTURA
    SET ID_CLIENTE = f_ID_CLIENTE
    WHERE ID_FACTURA = f_ID_FACTURA;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('La factura con el ID: ' || f_ID_FACTURA || ' ha sido modificado');

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_FACTURA(1,3);

/*---------SP para eliminar factura-------------------*/
--17
CREATE OR REPLACE PROCEDURE DELETE_FACTURA(
	   f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE)
AS
BEGIN

  DELETE FROM FACTURA
    WHERE ID_FACTURA = f_ID_FACTURA;
  DBMS_OUTPUT.PUT_LINE('La factura con ID: ' || f_ID_FACTURA || ' ha sido eliminada');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_FACTURA(5);

/*--------------------CRUD tabla CLASE---------------------------------------*/
/*---------SP para insertar clases-------------------*/
--18
CREATE OR REPLACE PROCEDURE INSERT_CLASE(
	   c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
       c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE,
	   c_ESTADO IN CLASES.ESTADO%TYPE,
	   c_ESPACIOS IN CLASES.ESPACIOS%TYPE,
	   c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE,
       c_ID_HORARIO IN CLASES.ID_HORARIO%TYPE)
IS
BEGIN

  INSERT INTO CLASES("ID_CLASE", "DESCRIPCION", "ESTADO", "ESPACIOS", "ID_EMPLEADO","ID_HORARIO") 
  VALUES (c_ID_CLASE, c_DESCRIPCION, c_ESTADO, c_ESPACIOS, c_ID_EMPLEADO, c_ID_HORARIO);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro para la clase con ID ' || c_ID_CLASE|| ' ha sido insertado');

END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_CLASE(4,'GAP','Activa',10,1,1);

/*---------SP para modificar el Empleado encargado de una clase segun el ID de la clase----*/
--19
CREATE OR REPLACE PROCEDURE UPDATE_CLASE_EMPLEADO(
	   c_ID_CLASE  IN CLASES.ID_CLASE %TYPE,
	   c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE)
AS
BEGIN

  UPDATE CLASES
    SET ID_EMPLEADO = c_ID_EMPLEADO
    WHERE ID_CLASE = c_ID_CLASE;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('EL encargado de impartir la clase ahora es el instructor con ID: ' || c_ID_EMPLEADO );

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_CLASE_EMPLEADO(4,3);

/*---------SP para eliminar clases-------------------*/
--20
CREATE OR REPLACE PROCEDURE DELETE_CLASE(
	   c_ID_CLASE IN CLASES.ID_CLASE%TYPE)
AS
BEGIN

  DELETE FROM CLASES
    WHERE ID_CLASE = c_ID_CLASE;
  DBMS_OUTPUT.PUT_LINE('La clase con el ID: ' || c_ID_CLASE || ' ha sido eliminada');

END;

/*---------------correr el procedimiento---------------*/
EXEC DELETE_CLASE(4)

---------------Trigger se dispara cuando una clase es eliminada---------------------4t--
CREATE OR REPLACE TRIGGER TGR_AUD_CLASES
BEFORE DELETE ON CLASES
FOR EACH ROW
BEGIN
    INSERT INTO AUD_CLASES(
        ID_CLASE,
        DESCRIPCION,
        ESTADO,
        ESPACIOS,
        ID_EMPLEADO,
        ID_HORARIO,
        ACCION
    ) VALUES (
        :old.ID_CLASE,
        :old.DESCRIPCION,
        :old.ESTADO,
        :old.ESPACIOS,
        :old.ID_EMPLEADO,
        :old.ID_HORARIO,
        'DELETE'
    );
END;

----------------Probar trigge--------------------------
EXEC DELETE_CLASE(3)

/*---------SP para modificar el nombre de la clase segun el ID ----*/
--21
CREATE OR REPLACE PROCEDURE UPDATE_CLASE_DESCRIPCION(
	   c_ID_CLASE  IN CLASES.ID_CLASE %TYPE,
	   c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE)
AS
BEGIN

  UPDATE CLASES
    SET DESCRIPCION = c_DESCRIPCION
    WHERE ID_CLASE = c_ID_CLASE;
    COMMIT;
  DBMS_OUTPUT.PUT_LINE('La clase con ID: ' || c_ID_CLASE || ' ahora se llama ' || c_DESCRIPCION);

END;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_CLASE_DESCRIPCION(2,'Kickbox');

/*--------------------CRUD tabla Empleado---------------------------------------*/
/*---------SP para insertar Empleados-------------------*/
--22
CREATE OR REPLACE PROCEDURE INSERT_EMPLEADO(
	   e_ID_EMPLEADO IN EMPLEADO.ID_EMPLEADO%TYPE,
	   e_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
	   e_APELLIDO IN EMPLEADO.APELLIDO%TYPE,
	   e_FECHA_INICIO IN EMPLEADO.FECHA_INICIO%TYPE,
	   e_ESTADO IN EMPLEADO.ESTADO%TYPE,
	   e_SALARIO IN EMPLEADO.SALARIO%TYPE,
	   e_EMAIL IN EMPLEADO.EMAIL%TYPE,
	   e_TELEFONO IN EMPLEADO.TELEFONO%TYPE,
	   e_PUESTO IN EMPLEADO.PUESTO%TYPE)
IS
BEGIN

  INSERT INTO EMPLEADO("ID_EMPLEADO", "NOMBRE", "APELLIDO", "FECHA_INICIO","ESTADO","SALARIO","EMAIL","TELEFONO","PUESTO") 
  VALUES (e_ID_EMPLEADO, e_NOMBRE, e_APELLIDO, e_FECHA_INICIO, e_ESTADO, e_SALARIO, e_EMAIL, e_TELEFONO, e_PUESTO);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('El registro del empleado ' || e_NOMBRE || ' ' || e_APELLIDO || ' ha sido insertado');

END;

/*---------------correr el procedimiento---------------*/
EXEC INSERT_EMPLEADO(4,'Lili','Valverde','10/11/2010','Activo',50000,'lil@.com',5462258, 'Oficinista');

/*---------------------trigger que se dispara cuando se inserta un nuevo empleado-----------5t--*/
CREATE OR REPLACE TRIGGER TGR_INSERT_EMPLEADO
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
    INSERT INTO AUD_EMPLEADO (
        ID_EMPLEADO,
        NOMBRE,
        APELLIDO,
        FECHA_INICIO,
        ESTADO,
        SALARIO,
        EMAIL,
        TELEFONO,
        PUESTO,
        ACCION
    ) VALUES (
        :NEW.ID_EMPLEADO,
        :NEW.NOMBRE,
        :NEW.APELLIDO,
        :NEW.FECHA_INICIO,
        :NEW.ESTADO,
        :NEW.SALARIO,
        :NEW.EMAIL,
        :NEW.TELEFONO,
        :NEW.PUESTO,
        'INSERT'
    );
END;

-------------------Probar trigger-----------------
EXEC INSERT_EMPLEADO(5,'Alex','Vega','10/11/2009','Inactivo',50000,'lil@.com',5462258, 'Oficinista');

/*---------SP para modificar el salario de un empleado----*/
--23
CREATE OR REPLACE PROCEDURE UPDATE_EMPLEADO_SALARIO 
AS
BEGIN
    FOR EMPLEADO IN (SELECT * FROM EMPLEADO) LOOP
        DECLARE
            anios_trabajados INT;
        BEGIN
            -- Calcular los anios
            SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, EMPLEADO.FECHA_INICIO) / 12) INTO anios_trabajados
            FROM DUAL;

            -- Incrementar salario si tiene mas de 5 anios a un 5%
            IF anios_trabajados > 5 THEN
                UPDATE EMPLEADO
                SET SALARIO = SALARIO * 1.05
                WHERE ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
            END IF;
        END;
    END LOOP;
    COMMIT;
END UPDATE_EMPLEADO_SALARIO;

/*---------------correr el procedimiento---------------*/
EXEC UPDATE_EMPLEADO_SALARIO;


--Eliminar empleado inactivo con SP
--24
CREATE OR REPLACE PROCEDURE EliminarEmpleadoInactivo AS
BEGIN
    -- Eliminar empleados inactivos
    DELETE FROM EMPLEADO WHERE ESTADO = 'Inactivo';
    
    -- Confirmar la transaccion
    COMMIT;
    
    -- Mostrar mensaje de inactivo
    DBMS_OUTPUT.PUT_LINE('Empleados inactivos eliminados correctamente.');
END EliminarEmpleadoInactivo;

/*---------------correr el procedimiento---------------*/
EXEC EliminarEmpleadoInactivo;
------------------------------------------------------------------------------

-------------------------------
-- Cursor para la tabla Clientes
DECLARE
    CURSOR c_cliente IS
        SELECT * FROM CLIENTE;
BEGIN
    FOR rec IN c_cliente LOOP
        DBMS_OUTPUT.PUT_LINE('ID_CLIENTE: ' || rec.ID_CLIENTE || ', NOMBRE: ' || rec.NOMBRE || ', APELLIDO: ' || rec.APELLIDO);
    END LOOP;
END;
exec 
   -- Cursor para la tabla AUD_CLIENTE
    DECLARE
    CURSOR c_aud_cliente IS
        SELECT * FROM AUD_CLIENTE;
BEGIN
    FOR rec IN c_aud_cliente LOOP
        DBMS_OUTPUT.PUT_LINE('CONSECUTIVO: ' || rec.CONSECUTIVO || ', ID_CLIENTE: ' || rec.ID_CLIENTE || ', NOMBRE: ' || rec.NOMBRE);
    END LOOP;
END;
    
    -- Cursor para la tabla MEMBRESIAS
DECLARE
    CURSOR c_membresias IS
        SELECT * FROM MEMBRESIAS;
BEGIN
    FOR rec IN c_membresias LOOP
        DBMS_OUTPUT.PUT_LINE('ID_MEMBRESIA: ' || rec.ID_MEMBRESIA || ', TIPO: ' || rec.TIPO || ', ESTADO: ' || rec.ESTADO);
    END LOOP;
END;

   -- Cursor para la tabla EMPLEADO
DECLARE
    CURSOR c_empleado IS
        SELECT * FROM EMPLEADO;
BEGIN
    FOR rec IN c_empleado LOOP
        DBMS_OUTPUT.PUT_LINE('ID_EMPLEADO: ' || rec.ID_EMPLEADO || ', NOMBRE: ' || rec.NOMBRE || ', APELLIDO: ' || rec.APELLIDO);
    END LOOP;
END;

   -- Cursor Auditar empleados--
DECLARE
    CURSOR c_aud_empleado IS
        SELECT * FROM AUD_EMPLEADO;
BEGIN
    FOR rec IN c_aud_empleado LOOP
        DBMS_OUTPUT.PUT_LINE('CONSECUTIVO: ' || rec.CONSECUTIVO || ', ID_EMPLEADO: ' || rec.ID_EMPLEADO || ', NOMBRE: ' || rec.NOMBRE);
    END LOOP;
END;
	
   -- Cursor Clases --
DECLARE
    CURSOR c_clases IS
        SELECT * FROM CLASES;
BEGIN
    FOR rec IN c_clases LOOP
        DBMS_OUTPUT.PUT_LINE('ID_CLASE: ' || rec.ID_CLASE || ', DESCRIPCION: ' || rec.DESCRIPCION || ', ESTADO: ' || rec.ESTADO);
    END LOOP;
END;

   --Cursor auditar clases--
DECLARE
    CURSOR c_aud_clases IS
        SELECT * FROM AUD_CLASES;
BEGIN
    FOR rec IN c_aud_clases LOOP
        DBMS_OUTPUT.PUT_LINE('CONSECUTIVO: ' || rec.CONSECUTIVO || ', ID_CLASE: ' || rec.ID_CLASE || ', DESCRIPCION: ' || rec.DESCRIPCION);
    END LOOP;
END;

   --Cursor reservas--
DECLARE
    CURSOR c_reservas IS
        SELECT * FROM RESERVAS;
BEGIN
    FOR rec IN c_reservas LOOP
        DBMS_OUTPUT.PUT_LINE('ID_RESERVA: ' || rec.ID_RESERVA || ', ESTADO: ' || rec.ESTADO || ', ID_CLASE: ' || rec.ID_CLASE);
    END LOOP;
END;

   --Cursor auditar reservas--
DECLARE
    CURSOR c_aud_reservas IS
        SELECT * FROM AUD_RESERVAS;
BEGIN
    FOR rec IN c_aud_reservas LOOP
        DBMS_OUTPUT.PUT_LINE('CONSECUTIVO: ' || rec.CONSECUTIVO || ', ID_RESERVA: ' || rec.ID_RESERVA || ', ESTADO: ' || rec.ESTADO);
    END LOOP;
END;

   --Cursor horarios--
DECLARE
    CURSOR c_horario IS
        SELECT * FROM HORARIO;
BEGIN
    FOR rec IN c_horario LOOP
        DBMS_OUTPUT.PUT_LINE('ID_HORARIO: ' || rec.ID_HORARIO || ', DIA: ' || rec.DIA || ', HORA_INICIO: ' || rec.HORA_INICIO);
    END LOOP;
END;

   --Cursor de facturas--
DECLARE
    CURSOR c_factura IS
        SELECT * FROM FACTURA;
BEGIN
    FOR rec IN c_factura LOOP
        DBMS_OUTPUT.PUT_LINE('ID_FACTURA: ' || rec.ID_FACTURA || ', ID_CLIENTE: ' || rec.ID_CLIENTE || ', MONTO: ' || rec.MONTO);
    END LOOP;
END;

   --Cursor para ver auditar facturas --
DECLARE
    CURSOR c_aud_factura IS
        SELECT * FROM AUD_FACTURA;
BEGIN
    FOR rec IN c_aud_factura LOOP
        DBMS_OUTPUT.PUT_LINE('ID_FACTURA: ' || rec.ID_FACTURA || ', ID_CLIENTE: ' || rec.ID_CLIENTE);
    END LOOP;
END;

--Cursor Facturas vencidas
DECLARE
    CURSOR c_facturas_vencidas IS
        SELECT *
        FROM FACTURA
        WHERE FECHA < SYSDATE; 

    rec_factura c_facturas_vencidas%ROWTYPE;
BEGIN
    OPEN c_facturas_vencidas;
    LOOP
        FETCH c_facturas_vencidas INTO rec_factura;
        EXIT WHEN c_facturas_vencidas%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('Factura Vencida - ID_FACTURA: ' || rec_factura.ID_FACTURA || ', ID_CLIENTE: ' || rec_factura.ID_CLIENTE || ', MONTO: ' || rec_factura.MONTO);
    END LOOP;
    CLOSE c_facturas_vencidas;
END;

--Cursor reservas pendientes
DECLARE
    CURSOR c_reservas_pendientes IS
        SELECT *
        FROM RESERVAS
        WHERE ESTADO = 'Pendiente'; 

    rec_reserva c_reservas_pendientes%ROWTYPE;
BEGIN
    OPEN c_reservas_pendientes;
    LOOP
        FETCH c_reservas_pendientes INTO rec_reserva;
        EXIT WHEN c_reservas_pendientes%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('Reserva Pendiente - ID_RESERVA: ' || rec_reserva.ID_RESERVA || ', ID_CLASE: ' || rec_reserva.ID_CLASE || ', ID_CLIENTE: ' || rec_reserva.ID_CLIENTE);
    END LOOP;
    CLOSE c_reservas_pendientes;
END;

--Cursor membresias vencidas
DECLARE
    CURSOR c_membresias_vencidas IS
        SELECT *
        FROM MEMBRESIAS
        WHERE FECHA_EXPIRACION < SYSDATE; -- Ajusta la condiciÃ³n segÃºn la estructura real de tu tabla

    rec_membresia c_membresias_vencidas%ROWTYPE;
BEGIN
    OPEN c_membresias_vencidas;
    LOOP
        FETCH c_membresias_vencidas INTO rec_membresia;
        EXIT WHEN c_membresias_vencidas%NOTFOUND;

        -- Realiza las operaciones que necesites con cada membresÃ­a vencida
        DBMS_OUTPUT.PUT_LINE('MembresÃ­a Vencida - ID_MEMBRESIA: ' || rec_membresia.ID_MEMBRESIA || ', ID_CLIENTE: ' || rec_membresia.ID_CLIENTE || ', FECHA_EXPIRACION: ' || rec_membresia.FECHA_EXPIRACION);
    END LOOP;
    CLOSE c_membresias_vencidas;
END;

        -- Insertar datos en la tabla RESERVAS**
BEGIN
    FOR reserva IN c_reservas
    LOOP
        INSERT INTO RESERVAS (ID_RESERVA, FECHA, HORA, ESTADO, ID_CLIENTE)
        VALUES (reserva.ID_RESERVA, reserva.FECHA, reserva.HORA, reserva.ESTADO, reserva.ID_CLIENTE);
    END LOOP;

    COMMIT; 
END;


BEGIN
-- Insertar datos en la tabla HORARIO**
    FOR horario IN c_horario
    LOOP
        INSERT INTO HORARIO (ID_HORARIO, DIA, HORA_INICIO, HORA_FIN, CLASE)
        VALUES (horario.ID_HORARIO, horario.DIA, horario.HORA_INICIO, horario.HORA_FIN, horario.CLASE);
    END LOOP;
END;

-- Crear una vista que incluya la informacion de la tabla CLIENTE 1
CREATE VIEW Vista_Cliente AS
SELECT
    ID_CLIENTE,
    NOMBRE,
    APELLIDO,
    FECHAINGRESO,
    MENSUALIDAD
FROM CLIENTE;

-- Consulta utilizando la vista
SELECT * FROM Vista_Cliente;

-- Crear una vista que incluya la informacion de la tabla MEMBRESIAS 2
CREATE VIEW Vista_Membresias AS
SELECT
    ID_MEMBRESIA,
    TIPO,
    ESTADO,
    FECHA_INICIO,
    FECHA_EXPIRACION,
    ID_CLIENTE
FROM MEMBRESIAS;

-- Consulta utilizando la vista
SELECT * FROM Vista_Membresias;

-- Crear una vista que incluya la informacion de la tabla EMPLEADO 3
CREATE VIEW Vista_Empleado AS
SELECT
    ID_EMPLEADO,
    NOMBRE,
    APELLIDO,
    FECHA_INICIO,
    ESTADO,
    SALARIO,
    EMAIL,
    TELEFONO,
    PUESTO
FROM EMPLEADO;


-- Consulta utilizando la vista
SELECT * FROM Vista_Empleado;

-- Crear una vista que incluya la informacion de la tabla RESERVAS 4
CREATE VIEW Vista_Reservas AS
SELECT
    ID_RESERVA,
    ESTADO,
    ID_CLASE,
    ID_CLIENTE
FROM RESERVAS;

-- Consulta utilizando la vista
SELECT * FROM Vista_Reservas;

-- Crear una vista que incluya la informacion de la tabla FACTURA 5
CREATE VIEW Vista_Factura AS
SELECT
    ID_FACTURA,
    ID_CLIENTE,
    MONTO,
    FECHA,
    DESCRIPCION
FROM FACTURA;

-- Consulta utilizando la vista
SELECT * FROM Vista_Factura;

--Vista Reservas Actuales 6
CREATE OR REPLACE VIEW VISTA_RESERVAS_ACTUALES AS
SELECT R.ID_RESERVA, R.ESTADO, C.NOMBRE AS NOMBRE_CLIENTE, CL.DESCRIPCION AS DESCRIPCION_CLASE
FROM RESERVAS R
JOIN CLIENTE C ON R.ID_CLIENTE = C.ID_CLIENTE
JOIN CLASES CL ON R.ID_CLASE = CL.ID_CLASE
WHERE R.ESTADO = 'Activa';

SELECT * FROM VISTA_RESERVAS_ACTUALES;

--Vista Membresias Activas 7
CREATE OR REPLACE VIEW VISTA_MEMBRESIAS_ACTIVAS AS
SELECT M.ID_MEMBRESIA, M.TIPO, M.ESTADO, C.NOMBRE AS NOMBRE_CLIENTE
FROM MEMBRESIAS M
JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
WHERE M.ESTADO = 'Activo';

SELECT * FROM VISTA_MEMBRESIAS_ACTIVAS;

--Vista para Instructor y su clase 8
CREATE OR REPLACE VIEW VISTA_INSTRUCTORES_CLASES AS
SELECT E.NOMBRE AS NOMBRE_INSTRUCTOR, E.PUESTO, CL.DESCRIPCION AS DESCRIPCION_CLASE
FROM EMPLEADO E
JOIN CLASES CL ON E.ID_EMPLEADO = CL.ID_EMPLEADO;

SELECT * FROM VISTA_INSTRUCTORES_CLASES;

--Vista para facturas emitidas 9
CREATE OR REPLACE VIEW VISTA_FACTURAS_EMITIDAS AS
SELECT F.ID_FACTURA, F.MONTO, F.FECHA, C.NOMBRE AS NOMBRE_CLIENTE
FROM FACTURA F
JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE;

SELECT * FROM VISTA_FACTURAS_EMITIDAS;

--Vista de Clientes y sus Membresias 10
CREATE OR REPLACE VIEW VISTA_CLIENTES_MEMBRESIAS AS
SELECT C.NOMBRE AS NOMBRE_CLIENTE, M.TIPO, M.FECHA_INICIO, M.FECHA_EXPIRACION
FROM CLIENTE C
JOIN MEMBRESIAS M ON C.ID_CLIENTE = M.ID_CLIENTE;

SELECT * FROM VISTA_CLIENTES_MEMBRESIAS;



--Funcion para ver todos los clientes--*************************
CREATE OR REPLACE FUNCTION GET_ALL_CLIENTES
RETURN SYS_REFCURSOR
IS
    cliente_cursor SYS_REFCURSOR;
BEGIN
    OPEN cliente_cursor FOR
        SELECT * FROM CLIENTE;
    RETURN cliente_cursor;
END;


--Funcion para obtener todas las reservas--********************
CREATE OR REPLACE FUNCTION GET_ALL_RESERVAS
RETURN SYS_REFCURSOR
IS
    reservas_cursor SYS_REFCURSOR;
BEGIN
    OPEN reservas_cursor FOR
        SELECT * FROM RESERVAS;
    RETURN reservas_cursor;
END;


--Funcion para obtener todas las facturas--******************************
CREATE OR REPLACE FUNCTION GET_ALL_FACTURAS
RETURN SYS_REFCURSOR
IS
    factura_cursor SYS_REFCURSOR;
BEGIN
    OPEN factura_cursor FOR
        SELECT * FROM FACTURA;
    RETURN factura_cursor;
END;

	
--Consulta horario--***************************
CREATE OR REPLACE FUNCTION GET_ALL_HORARIOS
RETURN SYS_REFCURSOR
IS
    horario_cursor SYS_REFCURSOR;
BEGIN
    OPEN horario_cursor FOR
        SELECT * FROM HORARIO;
    RETURN horario_cursor;
END;


--Consulta de facturas--********************
CREATE OR REPLACE FUNCTION GET_ALL_FACTURAS
RETURN SYS_REFCURSOR
IS
    factura_cursor SYS_REFCURSOR;
BEGIN
    OPEN factura_cursor FOR
        SELECT * FROM FACTURA;
    RETURN factura_cursor;
END;

--Consulta de Empleados
CREATE OR REPLACE FUNCTION GET_ALL_EMPLEADOS
RETURN SYS_REFCURSOR
IS
    empleados_cursor SYS_REFCURSOR;
BEGIN
    OPEN empleados_cursor FOR
        SELECT * FROM EMPLEADO;
    RETURN empleados_cursor;
END;

--
--PAQUETES--
--Paquete sobre clientes 
CREATE OR REPLACE PACKAGE ClientePackage AS
  -- Procedimiento para insertar un cliente
  PROCEDURE InsertCliente(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_NOMBRE IN CLIENTE.NOMBRE%TYPE,
    c_APELLIDO IN CLIENTE.APELLIDO %TYPE,
    c_FECHAINGRESO IN CLIENTE.FECHAINGRESO%TYPE,
    c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE
  );

  -- Procedimiento para actualizar la mensualidad de un cliente
  PROCEDURE UpdateClienteMensualidad(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE
  );

  -- Procedimiento para actualizar el nombre de un cliente
  PROCEDURE UpdateClienteNombre(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_NOMBRE IN CLIENTE.NOMBRE%TYPE
  );

  -- Procedimiento para eliminar un cliente
  PROCEDURE DeleteCliente(c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE);
END ClientePackage;

CREATE OR REPLACE PACKAGE BODY ClientePackage AS
  -- Implementación del procedimiento para insertar un cliente
  PROCEDURE InsertCliente(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_NOMBRE IN CLIENTE.NOMBRE%TYPE,
    c_APELLIDO IN CLIENTE.APELLIDO %TYPE,
    c_FECHAINGRESO IN CLIENTE.FECHAINGRESO%TYPE,
    c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE
  ) AS
  BEGIN
    INSERT INTO CLIENTE ("ID_CLIENTE", "NOMBRE", "APELLIDO", "FECHAINGRESO","MENSUALIDAD") 
    VALUES (c_ID_CLIENTE, c_NOMBRE, c_APELLIDO, c_FECHAINGRESO, c_MENSUALIDAD);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro de ' || c_NOMBRE || ' ha sido insertado');
  END;

  -- Implementación del procedimiento para actualizar la mensualidad de un cliente
  PROCEDURE UpdateClienteMensualidad(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_MENSUALIDAD IN CLIENTE.MENSUALIDAD%TYPE
  ) AS
  BEGIN
    UPDATE CLIENTE
      SET MENSUALIDAD = c_MENSUALIDAD
      WHERE ID_CLIENTE = c_ID_CLIENTE;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido modificado');
  END;

  -- Implementación del procedimiento para actualizar el nombre de un cliente
  PROCEDURE UpdateClienteNombre(
    c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE,
    c_NOMBRE IN CLIENTE.NOMBRE%TYPE
  ) AS
  BEGIN
    UPDATE CLIENTE
      SET NOMBRE = c_NOMBRE
      WHERE ID_CLIENTE = c_ID_CLIENTE;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido modificado');
  END;

  -- Implementación del procedimiento para eliminar un cliente
  PROCEDURE DeleteCliente(c_ID_CLIENTE IN CLIENTE.ID_CLIENTE%TYPE) AS
  BEGIN
    DELETE FROM CLIENTE
      WHERE ID_CLIENTE = c_ID_CLIENTE;
    DBMS_OUTPUT.PUT_LINE('El registro del cliente con ID: ' || c_ID_CLIENTE || ' ha sido eliminado');
  END;
END ClientePackage;


-- Ejecutar el procedimiento para insertar un cliente
EXEC ClientePackage.InsertCliente(5, 'Andres', 'Soza', TO_DATE('09/10/2010', 'MM/DD/YYYY'), 2);

-- Ejecutar el procedimiento para actualizar la mensualidad de un cliente
EXEC ClientePackage.UpdateClienteMensualidad(6, 2);

-- Ejecutar el procedimiento para actualizar el nombre de un cliente
EXEC ClientePackage.UpdateClienteNombre(2, 'Lucas');

-- Ejecutar el procedimiento para eliminar un cliente
EXEC ClientePackage.DeleteCliente(6);

--Paquete Reservas
CREATE OR REPLACE PACKAGE ReservaPackage AS
  -- Procedimiento para insertar una reserva
  PROCEDURE InsertReserva(
    r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE,
    r_ESTADO_RESERVA IN RESERVAS.ESTADO%TYPE,
    r_ID_CLASE IN RESERVAS.ID_CLASE%TYPE,
    r_ID_CLIENTE IN RESERVAS.ID_CLIENTE%TYPE
  );

  -- Procedimiento para actualizar el estado de una reserva
  PROCEDURE UpdateReservaEstado(
    r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE,
    r_ESTADO IN RESERVAS.ESTADO%TYPE
  );

  -- Procedimiento para eliminar una reserva
  PROCEDURE DeleteReserva(r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE);
END ReservaPackage;

CREATE OR REPLACE PACKAGE BODY ReservaPackage AS
  -- Implementación del procedimiento para insertar una reserva
  PROCEDURE InsertReserva(
    r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE,
    r_ESTADO_RESERVA IN RESERVAS.ESTADO%TYPE,
    r_ID_CLASE IN RESERVAS.ID_CLASE%TYPE,
    r_ID_CLIENTE IN RESERVAS.ID_CLIENTE%TYPE
  ) AS
    c_ESPACIOS_DISPONIBLES INT;
  BEGIN
    --Cuantos espacios hay disponibles en la clase
    SELECT ESPACIOS INTO c_ESPACIOS_DISPONIBLES
    FROM CLASES
    WHERE ID_CLASE = r_ID_CLASE;

    IF c_ESPACIOS_DISPONIBLES > 0 THEN
      --Si hay espacios, se inserta la reserva
      INSERT INTO RESERVAS (
        ID_RESERVA,
        ESTADO,
        ID_CLASE,
        ID_CLIENTE
      ) VALUES (
        r_ID_RESERVA,
        r_ESTADO_RESERVA,
        r_ID_CLASE,
        r_ID_CLIENTE
      );

      --Se actualiza la tabla Clases y se elimina un espacio
      UPDATE CLASES
      SET ESPACIOS = c_ESPACIOS_DISPONIBLES - 1
      WHERE ID_CLASE = r_ID_CLASE;

      COMMIT;
      DBMS_OUTPUT.PUT_LINE('La reserva fue creada y se redujo un espacio en la clase ' || r_ID_CLASE);
    ELSE
      -- Si no hay espacio
      DBMS_OUTPUT.PUT_LINE('No hay suficiente espacio para esta clase.');
    END IF;
  END InsertReserva;

  -- Implementación del procedimiento para actualizar el estado de una reserva
  PROCEDURE UpdateReservaEstado(
    r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE,
    r_ESTADO IN RESERVAS.ESTADO%TYPE
  ) AS
  BEGIN
    UPDATE RESERVAS
      SET ESTADO = r_ESTADO
      WHERE ID_RESERVA = r_ID_RESERVA;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro del estado con ID: ' || r_ID_RESERVA || ' ha sido modificado');
  END UpdateReservaEstado;

  -- Implementación del procedimiento para eliminar una reserva
  PROCEDURE DeleteReserva(r_ID_RESERVA IN RESERVAS.ID_RESERVA%TYPE) AS
  BEGIN
    DELETE FROM RESERVAS
      WHERE ID_RESERVA = r_ID_RESERVA;

    DBMS_OUTPUT.PUT_LINE('La reserva con ID: ' || r_ID_RESERVA || ' ha sido eliminada');
  END DeleteReserva;
END ReservaPackage;

-- Ejecutar el procedimiento para insertar una reserva
EXEC ReservaPackage.InsertReserva(5, 'Activa', 3, 3);

-- Ejecutar el procedimiento para actualizar el estado de una reserva
EXEC ReservaPackage.UpdateReservaEstado(1, 'Pendiente');

-- Ejecutar el procedimiento para eliminar una reserva
EXEC ReservaPackage.DeleteReserva(4);


--Paquete Membresias--
CREATE OR REPLACE PACKAGE Membresia_Package AS

  /* Procedimiento para insertar una membresÃ­a */
  PROCEDURE INSERT_MEMBRESIA(
    m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA%TYPE,
    m_TIPO IN MEMBRESIAS.TIPO%TYPE,
    m_ESTADO IN MEMBRESIAS.ESTADO%TYPE,
    m_FECHA_INICIO IN MEMBRESIAS.FECHA_INICIO%TYPE,
    m_FECHA_EXPIRACION IN MEMBRESIAS.FECHA_EXPIRACION%TYPE,
    m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE
  );

  /* Procedimiento para actualizar el estado de una membresÃ­a por ID de cliente */
  PROCEDURE UPDATE_MEMBRESIAS(
    m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE,
    m_ESTADO IN MEMBRESIAS.ESTADO%TYPE
  );

  /* Procedimiento para eliminar una membresÃ­a por ID de membresÃ­a */
  PROCEDURE DELETE_MEMBRESIA(
    m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA%TYPE
  );

END Membresia_Package;

CREATE OR REPLACE PACKAGE BODY Membresia_Package AS

  /* Implementacion del procedimiento para insertar una membresia */
  PROCEDURE INSERT_MEMBRESIA(
    m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA%TYPE,
    m_TIPO IN MEMBRESIAS.TIPO%TYPE,
    m_ESTADO IN MEMBRESIAS.ESTADO%TYPE,
    m_FECHA_INICIO IN MEMBRESIAS.FECHA_INICIO%TYPE,
    m_FECHA_EXPIRACION IN MEMBRESIAS.FECHA_EXPIRACION%TYPE,
    m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE
  )
  IS
  BEGIN
    INSERT INTO MEMBRESIAS("ID_MEMBRESIA", "TIPO", "ESTADO", "FECHA_INICIO", "FECHA_EXPIRACION", "ID_CLIENTE")
    VALUES (m_ID_MEMBRESIA, m_TIPO, m_ESTADO, m_FECHA_INICIO, m_FECHA_EXPIRACION, m_ID_CLIENTE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro de ' || m_ID_MEMBRESIA || ' ha sido insertado');
  END;

  /* Implementacion del procedimiento para actualizar el estado de una membresia por ID de cliente */
  PROCEDURE UPDATE_MEMBRESIAS(
    m_ID_CLIENTE IN MEMBRESIAS.ID_CLIENTE%TYPE,
    m_ESTADO IN MEMBRESIAS.ESTADO%TYPE
  )
  AS
  BEGIN
    UPDATE MEMBRESIAS
    SET ESTADO = m_ESTADO
    WHERE ID_CLIENTE = m_ID_CLIENTE;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El estado de la membresÃ­a del cliente con ID: ' || m_ID_CLIENTE || ' ha sido modificado');
  END;

  /* Implementacion del procedimiento para eliminar una membresia por ID de membresÃ­a */
  PROCEDURE DELETE_MEMBRESIA(
    m_ID_MEMBRESIA IN MEMBRESIAS.ID_MEMBRESIA%TYPE
  )
  AS
  BEGIN
    DELETE FROM MEMBRESIAS
    WHERE ID_MEMBRESIA = m_ID_MEMBRESIA;
    DBMS_OUTPUT.PUT_LINE('El registro de la membresÃ­a con ID: ' || m_ID_MEMBRESIA || ' ha sido eliminado');
  END;

END Membresia_Package;

-- Ejemplo de ejecuciÃ³n del procedimiento INSERT_MEMBRESIA
EXEC Membresia_Package.INSERT_MEMBRESIA(5, 'Premium', 'Activo', TO_DATE('10/11/2023', 'DD/MM/YYYY'), TO_DATE('10/12/2023', 'DD/MM/YYYY'), 5);

-- Ejemplo de ejecuciÃ³n del procedimiento UPDATE_MEMBRESIAS
EXEC Membresia_Package.UPDATE_MEMBRESIAS(3, 'Inactivo');

-- Ejemplo de ejecuciÃ³n del procedimiento DELETE_MEMBRESIA
EXEC Membresia_Package.DELETE_MEMBRESIA(4);

--Paquete Horario
CREATE OR REPLACE PACKAGE HorarioPackage AS
  -- Procedimiento para insertar un horario
  PROCEDURE InsertHorario(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_DIA IN HORARIO.DIA%TYPE,
    h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE,
    h_HORA_FIN IN HORARIO.HORA_FIN%TYPE
  );

  -- Procedimiento para actualizar el día de un horario
  PROCEDURE UpdateHorarioDia(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_DIA IN HORARIO.DIA%TYPE
  );

  -- Procedimiento para actualizar la hora de inicio de un horario
  PROCEDURE UpdateHorarioInicio(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE
  );

  -- Procedimiento para actualizar la hora de finalización de un horario
  PROCEDURE UpdateHorarioFin(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_HORA_FIN IN HORARIO.HORA_FIN%TYPE
  );

  -- Procedimiento para eliminar un horario
  PROCEDURE DeleteHorario(h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE);
END HorarioPackage;

CREATE OR REPLACE PACKAGE BODY HorarioPackage AS
  -- Implementación del procedimiento para insertar un horario
  PROCEDURE InsertHorario(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_DIA IN HORARIO.DIA%TYPE,
    h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE,
    h_HORA_FIN IN HORARIO.HORA_FIN%TYPE
  ) AS
  BEGIN
    INSERT INTO HORARIO (ID_HORARIO, DIA, HORA_INICIO, HORA_FIN)
    VALUES (h_ID_HORARIO, h_DIA, h_HORA_INICIO, h_HORA_FIN);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El horario con ID: ' || h_ID_HORARIO || ' ha sido insertado.');
  END InsertHorario;

  -- Implementación del procedimiento para actualizar el día de un horario
  PROCEDURE UpdateHorarioDia(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_DIA IN HORARIO.DIA%TYPE
  ) AS
  BEGIN
    UPDATE HORARIO
      SET DIA = h_DIA
      WHERE ID_HORARIO = h_ID_HORARIO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El día para el horario con ID: ' || h_ID_HORARIO || ' ha sido modificado');
  END UpdateHorarioDia;

  -- Implementación del procedimiento para actualizar la hora de inicio de un horario
  PROCEDURE UpdateHorarioInicio(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_HORA_INICIO IN HORARIO.HORA_INICIO%TYPE
  ) AS
  BEGIN
    UPDATE HORARIO
      SET HORA_INICIO = h_HORA_INICIO
      WHERE ID_HORARIO = h_ID_HORARIO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('La hora de inicio para el horario con ID: ' || h_ID_HORARIO || ' ha sido modificada a ' || h_HORA_INICIO);
  END UpdateHorarioInicio;

  -- Implementación del procedimiento para actualizar la hora de finalización de un horario
  PROCEDURE UpdateHorarioFin(
    h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE,
    h_HORA_FIN IN HORARIO.HORA_FIN%TYPE
  ) AS
  BEGIN
    UPDATE HORARIO
      SET HORA_FIN = h_HORA_FIN
      WHERE ID_HORARIO = h_ID_HORARIO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('La hora de finalización para el horario con ID: ' || h_ID_HORARIO || ' ha sido modificada a ' || h_HORA_FIN);
  END UpdateHorarioFin;

  -- Implementación del procedimiento para eliminar un horario
  PROCEDURE DeleteHorario(h_ID_HORARIO IN HORARIO.ID_HORARIO%TYPE) AS
  BEGIN
    DELETE FROM HORARIO
      WHERE ID_HORARIO = h_ID_HORARIO;

    DBMS_OUTPUT.PUT_LINE('El horario con ID: ' || h_ID_HORARIO || ' ha sido eliminado');
  END DeleteHorario;
END HorarioPackage;

-- Ejecutar el procedimiento para insertar un horario
EXEC HorarioPackage.InsertHorario(4, 'Miercoles', TO_TIMESTAMP('18:00', 'HH24:MI:SS'), TO_TIMESTAMP('20:00', 'HH24:MI:SS'));

-- Ejecutar el procedimiento para actualizar el día de un horario
EXEC HorarioPackage.UpdateHorarioDia(3, 'Lunes');

-- Ejecutar el procedimiento para actualizar la hora de inicio de un horario
EXEC HorarioPackage.UpdateHorarioInicio(3, TO_TIMESTAMP('14:00', 'HH24:MI:SS'));

-- Ejecutar el procedimiento para actualizar la hora de finalización de un horario
EXEC HorarioPackage.UpdateHorarioFin(3, TO_TIMESTAMP('18:00', 'HH24:MI:SS'));

-- Ejecutar el procedimiento para eliminar un horario
EXEC HorarioPackage.DeleteHorario(4);

--Paquete Facturas
CREATE OR REPLACE PACKAGE FacturaPackage AS
  -- Procedimiento para insertar una factura
  PROCEDURE InsertFactura(
    f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
    f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE,
    f_MONTO IN FACTURA.MONTO%TYPE,
    f_FECHA IN FACTURA.FECHA%TYPE,
    f_DESCRIPCION IN FACTURA.DESCRIPCION%TYPE
  );

  -- Procedimiento para actualizar el cliente en la tabla FACTURA
  PROCEDURE UpdateFactura(
    f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
    f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE
  );

  -- Procedimiento para eliminar una factura
  PROCEDURE DeleteFactura(f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE);
END FacturaPackage;

CREATE OR REPLACE PACKAGE BODY FacturaPackage AS
  -- Implementación del procedimiento para insertar una factura
  PROCEDURE InsertFactura(
    f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
    f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE,
    f_MONTO IN FACTURA.MONTO%TYPE,
    f_FECHA IN FACTURA.FECHA%TYPE,
    f_DESCRIPCION IN FACTURA.DESCRIPCION%TYPE
  ) AS
  BEGIN
    INSERT INTO FACTURA(ID_FACTURA, ID_CLIENTE, MONTO, FECHA, DESCRIPCION)
    VALUES (f_ID_FACTURA, f_ID_CLIENTE, f_MONTO, f_FECHA, f_DESCRIPCION);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro de factura con ID: ' || f_ID_FACTURA || ' ha sido insertado.');
  END InsertFactura;

  -- Implementación del procedimiento para actualizar el cliente en la tabla FACTURA
  PROCEDURE UpdateFactura(
    f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE,
    f_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE
  ) AS
  BEGIN
    UPDATE FACTURA
      SET ID_CLIENTE = f_ID_CLIENTE
      WHERE ID_FACTURA = f_ID_FACTURA;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('La factura con el ID: ' || f_ID_FACTURA || ' ha sido modificado');
  END UpdateFactura;

  -- Implementación del procedimiento para eliminar una factura
  PROCEDURE DeleteFactura(f_ID_FACTURA IN FACTURA.ID_FACTURA%TYPE) AS
  BEGIN
    DELETE FROM FACTURA
      WHERE ID_FACTURA = f_ID_FACTURA;

    DBMS_OUTPUT.PUT_LINE('La factura con ID: ' || f_ID_FACTURA || ' ha sido eliminada');
  END DeleteFactura;
END FacturaPackage;

-- Ejecutar el procedimiento para insertar una factura
EXEC FacturaPackage.InsertFactura(4, 2, 50000, TO_DATE('2023-10-30', 'YYYY-MM-DD'), 'Pago de membresia');

-- Ejecutar el procedimiento para actualizar el cliente en la tabla FACTURA
EXEC FacturaPackage.UpdateFactura(1, 3);

-- Ejecutar el procedimiento para eliminar una factura
EXEC FacturaPackage.DeleteFactura(5);

--Paquete Clase
CREATE OR REPLACE PACKAGE ClasePackage AS
  -- Procedimiento para insertar una clase
  PROCEDURE InsertClase(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE,
    c_ESTADO IN CLASES.ESTADO%TYPE,
    c_ESPACIOS IN CLASES.ESPACIOS%TYPE,
    c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE,
    c_ID_HORARIO IN CLASES.ID_HORARIO%TYPE
  );

  -- Procedimiento para actualizar el empleado encargado de una clase
  PROCEDURE UpdateClaseEmpleado(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE
  );

  -- Procedimiento para eliminar una clase
  PROCEDURE DeleteClase(c_ID_CLASE IN CLASES.ID_CLASE%TYPE);

  -- Procedimiento para modificar el nombre de la clase
  PROCEDURE UpdateClaseDescripcion(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE
  );
END ClasePackage;


CREATE OR REPLACE PACKAGE BODY ClasePackage AS
  -- Implementación del procedimiento para insertar una clase
  PROCEDURE InsertClase(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE,
    c_ESTADO IN CLASES.ESTADO%TYPE,
    c_ESPACIOS IN CLASES.ESPACIOS%TYPE,
    c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE,
    c_ID_HORARIO IN CLASES.ID_HORARIO%TYPE
  ) AS
  BEGIN
    INSERT INTO CLASES("ID_CLASE", "DESCRIPCION", "ESTADO", "ESPACIOS", "ID_EMPLEADO", "ID_HORARIO") 
    VALUES (c_ID_CLASE, c_DESCRIPCION, c_ESTADO, c_ESPACIOS, c_ID_EMPLEADO, c_ID_HORARIO);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro para la clase con ID ' || c_ID_CLASE || ' ha sido insertado');
  END InsertClase;

  -- Implementación del procedimiento para actualizar el empleado encargado de una clase
  PROCEDURE UpdateClaseEmpleado(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_ID_EMPLEADO IN CLASES.ID_EMPLEADO%TYPE
  ) AS
  BEGIN
    UPDATE CLASES
      SET ID_EMPLEADO = c_ID_EMPLEADO
      WHERE ID_CLASE = c_ID_CLASE;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El encargado de impartir la clase ahora es el instructor con ID: ' || c_ID_EMPLEADO);
  END UpdateClaseEmpleado;

  -- Implementación del procedimiento para eliminar una clase
  PROCEDURE DeleteClase(c_ID_CLASE IN CLASES.ID_CLASE%TYPE) AS
  BEGIN
    DELETE FROM CLASES
      WHERE ID_CLASE = c_ID_CLASE;

    DBMS_OUTPUT.PUT_LINE('La clase con el ID: ' || c_ID_CLASE || ' ha sido eliminada');
  END DeleteClase;

  -- Implementación del procedimiento para modificar el nombre de la clase
  PROCEDURE UpdateClaseDescripcion(
    c_ID_CLASE IN CLASES.ID_CLASE%TYPE,
    c_DESCRIPCION IN CLASES.DESCRIPCION%TYPE
  ) AS
  BEGIN
    UPDATE CLASES
      SET DESCRIPCION = c_DESCRIPCION
      WHERE ID_CLASE = c_ID_CLASE;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('La clase con ID: ' || c_ID_CLASE || ' ahora se llama ' || c_DESCRIPCION);
  END UpdateClaseDescripcion;
END ClasePackage;

-- Ejecutar el procedimiento para insertar una clase
EXEC ClasePackage.InsertClase(4, 'GAP', 'Activa', 10, 1, 1);

-- Ejecutar el procedimiento para actualizar el empleado encargado de una clase
EXEC ClasePackage.UpdateClaseEmpleado(4, 3);

-- Ejecutar el procedimiento para eliminar una clase
EXEC ClasePackage.DeleteClase(4);

-- Ejecutar el procedimiento para modificar el nombre de la clase
EXEC ClasePackage.UpdateClaseDescripcion(2, 'Kickbox');

--Paquete Empleado
CREATE OR REPLACE PACKAGE EmpleadoPackage AS
  -- Procedimiento para insertar un empleado
  PROCEDURE InsertEmpleado(
    e_ID_EMPLEADO IN EMPLEADO.ID_EMPLEADO%TYPE,
    e_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
    e_APELLIDO IN EMPLEADO.APELLIDO%TYPE,
    e_FECHA_INICIO IN EMPLEADO.FECHA_INICIO%TYPE,
    e_ESTADO IN EMPLEADO.ESTADO%TYPE,
    e_SALARIO IN EMPLEADO.SALARIO%TYPE,
    e_EMAIL IN EMPLEADO.EMAIL%TYPE,
    e_TELEFONO IN EMPLEADO.TELEFONO%TYPE,
    e_PUESTO IN EMPLEADO.PUESTO%TYPE
  );

  -- Procedimiento para modificar el salario de los empleados
  PROCEDURE UpdateEmpleadoSalario;

  -- Procedimiento para eliminar empleados inactivos
  PROCEDURE EliminarEmpleadoInactivo;
END EmpleadoPackage;

CREATE OR REPLACE PACKAGE BODY EmpleadoPackage AS
  -- Implementación del procedimiento para insertar un empleado
  PROCEDURE InsertEmpleado(
    e_ID_EMPLEADO IN EMPLEADO.ID_EMPLEADO%TYPE,
    e_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
    e_APELLIDO IN EMPLEADO.APELLIDO%TYPE,
    e_FECHA_INICIO IN EMPLEADO.FECHA_INICIO%TYPE,
    e_ESTADO IN EMPLEADO.ESTADO%TYPE,
    e_SALARIO IN EMPLEADO.SALARIO%TYPE,
    e_EMAIL IN EMPLEADO.EMAIL%TYPE,
    e_TELEFONO IN EMPLEADO.TELEFONO%TYPE,
    e_PUESTO IN EMPLEADO.PUESTO%TYPE
  ) AS
  BEGIN
    INSERT INTO EMPLEADO(
      "ID_EMPLEADO",
      "NOMBRE",
      "APELLIDO",
      "FECHA_INICIO",
      "ESTADO",
      "SALARIO",
      "EMAIL",
      "TELEFONO",
      "PUESTO"
    ) 
    VALUES (
      e_ID_EMPLEADO,
      e_NOMBRE,
      e_APELLIDO,
      e_FECHA_INICIO,
      e_ESTADO,
      e_SALARIO,
      e_EMAIL,
      e_TELEFONO,
      e_PUESTO
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro del empleado ' || e_NOMBRE || ' ' || e_APELLIDO || ' ha sido insertado');
  END InsertEmpleado;

  -- Implementación del procedimiento para modificar el salario de los empleados
  PROCEDURE UpdateEmpleadoSalario AS
  BEGIN
    FOR EMPLEADO IN (SELECT * FROM EMPLEADO) LOOP
      DECLARE
        anios_trabajados INT;
      BEGIN
        -- Calcular los años
        SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, EMPLEADO.FECHA_INICIO) / 12) INTO anios_trabajados
        FROM DUAL;

        -- Incrementar salario si tiene más de 5 años a un 5%
        IF anios_trabajados > 5 THEN
          UPDATE EMPLEADO
          SET SALARIO = SALARIO * 1.05
          WHERE ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
        END IF;
      END;
    END LOOP;
    COMMIT;
  END UpdateEmpleadoSalario;

  -- Implementación del procedimiento para eliminar empleados inactivos
  PROCEDURE EliminarEmpleadoInactivo AS
  BEGIN
    -- Eliminar empleados inactivos
    DELETE FROM EMPLEADO WHERE ESTADO = 'Inactivo';
    
    -- Confirmar la transacción
    COMMIT;
    
    -- Mostrar mensaje de inactivos
    DBMS_OUTPUT.PUT_LINE('Empleados inactivos eliminados correctamente.');
  END EliminarEmpleadoInactivo;
END EmpleadoPackage;

CREATE OR REPLACE PACKAGE EmpleadoPackage AS
  -- Procedimiento para insertar un empleado
  PROCEDURE InsertEmpleado(
    e_ID_EMPLEADO IN EMPLEADO.ID_EMPLEADO%TYPE,
    e_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
    e_APELLIDO IN EMPLEADO.APELLIDO%TYPE,
    e_FECHA_INICIO IN EMPLEADO.FECHA_INICIO%TYPE,
    e_ESTADO IN EMPLEADO.ESTADO%TYPE,
    e_SALARIO IN EMPLEADO.SALARIO%TYPE,
    e_EMAIL IN EMPLEADO.EMAIL%TYPE,
    e_TELEFONO IN EMPLEADO.TELEFONO%TYPE,
    e_PUESTO IN EMPLEADO.PUESTO%TYPE
  );

  -- Procedimiento para modificar el salario de los empleados
  PROCEDURE UpdateEmpleadoSalario;

  -- Procedimiento para eliminar empleados inactivos
  PROCEDURE EliminarEmpleadoInactivo;
END EmpleadoPackage;
/

CREATE OR REPLACE PACKAGE BODY EmpleadoPackage AS
  -- Implementación del procedimiento para insertar un empleado
  PROCEDURE InsertEmpleado(
    e_ID_EMPLEADO IN EMPLEADO.ID_EMPLEADO%TYPE,
    e_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
    e_APELLIDO IN EMPLEADO.APELLIDO%TYPE,
    e_FECHA_INICIO IN EMPLEADO.FECHA_INICIO%TYPE,
    e_ESTADO IN EMPLEADO.ESTADO%TYPE,
    e_SALARIO IN EMPLEADO.SALARIO%TYPE,
    e_EMAIL IN EMPLEADO.EMAIL%TYPE,
    e_TELEFONO IN EMPLEADO.TELEFONO%TYPE,
    e_PUESTO IN EMPLEADO.PUESTO%TYPE
  ) AS
  BEGIN
    INSERT INTO EMPLEADO(
      "ID_EMPLEADO",
      "NOMBRE",
      "APELLIDO",
      "FECHA_INICIO",
      "ESTADO",
      "SALARIO",
      "EMAIL",
      "TELEFONO",
      "PUESTO"
    ) 
    VALUES (
      e_ID_EMPLEADO,
      e_NOMBRE,
      e_APELLIDO,
      e_FECHA_INICIO,
      e_ESTADO,
      e_SALARIO,
      e_EMAIL,
      e_TELEFONO,
      e_PUESTO
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('El registro del empleado ' || e_NOMBRE || ' ' || e_APELLIDO || ' ha sido insertado');
  END InsertEmpleado;

  -- Implementación del procedimiento para modificar el salario de los empleados
  PROCEDURE UpdateEmpleadoSalario AS
  BEGIN
    FOR EMPLEADO IN (SELECT * FROM EMPLEADO) LOOP
      DECLARE
        anios_trabajados INT;
      BEGIN
        -- Calcular los años
        SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, EMPLEADO.FECHA_INICIO) / 12) INTO anios_trabajados
        FROM DUAL;

        -- Incrementar salario si tiene más de 5 años a un 5%
        IF anios_trabajados > 5 THEN
          UPDATE EMPLEADO
          SET SALARIO = SALARIO * 1.05
          WHERE ID_EMPLEADO = EMPLEADO.ID_EMPLEADO;
        END IF;
      END;
    END LOOP;
    COMMIT;
  END UpdateEmpleadoSalario;

  -- Implementación del procedimiento para eliminar empleados inactivos
  PROCEDURE EliminarEmpleadoInactivo AS
  BEGIN
    -- Eliminar empleados inactivos
    DELETE FROM EMPLEADO WHERE ESTADO = 'Inactivo';
    
    -- Confirmar la transacción
    COMMIT;
    
    -- Mostrar mensaje de inactivos
    DBMS_OUTPUT.PUT_LINE('Empleados inactivos eliminados correctamente.');
  END EliminarEmpleadoInactivo;
END EmpleadoPackage;

-- Ejecutar el procedimiento para insertar un empleado
EXEC EmpleadoPackage.InsertEmpleado(4, 'Lili', 'Valverde', TO_DATE('10/11/2010', 'MM/DD/YYYY'), 'Activo', 50000, 'lil@.com', 5462258, 'Oficinista');

-- Ejecutar el procedimiento para modificar el salario de los empleados
EXEC EmpleadoPackage.UpdateEmpleadoSalario;

-- Ejecutar el procedimiento para eliminar empleados inactivos
EXEC EmpleadoPackage.EliminarEmpleadoInactivo;

--Paquetes de trigger
CREATE OR REPLACE PACKAGE TriggersPackage AS
  -- Trigger para actualizar la fecha de último movimiento en la tabla AUD_CLIENTE
  CREATE OR REPLACE NONEDITIONABLE TRIGGER Trg_Actualizar_Fecha_Ultimo_Mov
  BEFORE INSERT OR UPDATE OR DELETE ON AUD_CLIENTE
  FOR EACH ROW
  BEGIN
    :new.FECHA_MOV := CURRENT_TIMESTAMP;
  END Trg_Actualizar_Fecha_Ultimo_Mov;

  -- Trigger para renovar automáticamente la membresía
  CREATE OR REPLACE NONEDITIONABLE TRIGGER Trg_Renovar_Membresia
  BEFORE INSERT ON MEMBRESIAS
  FOR EACH ROW
  DECLARE
    v_fecha_actual DATE;
  BEGIN
    -- Obtener la fecha actual
    SELECT SYSDATE INTO v_fecha_actual FROM DUAL;

    -- Verificar si la fecha de vencimiento ha llegado
    IF :new.FECHA_EXPIRACION <= v_fecha_actual THEN
      -- Calcular la nueva fecha de inicio y de vencimiento para la renovación
      :new.FECHA_INICIO := v_fecha_actual;
      :new.FECHA_EXPIRACION := ADD_MONTHS(v_fecha_actual, 1); -- Por ejemplo, renovación por un mes

      -- Opcional: Mostrar un mensaje de éxito en la consola de salida
      DBMS_OUTPUT.PUT_LINE('Membresía renovada automáticamente.');
    END IF;
  END Trg_Renovar_Membresia;

  -- Trigger para verificar el vencimiento de la membresía
  CREATE OR REPLACE NONEDITIONABLE TRIGGER Trg_Vencimiento_Membresia
  BEFORE INSERT OR UPDATE ON MEMBRESIAS
  FOR EACH ROW
  DECLARE
    t_fecha_actual DATE;
  BEGIN
    -- Obtener la fecha actual
    SELECT SYSDATE INTO t_fecha_actual FROM DUAL;

    -- Verificar si la fecha de vencimiento ha pasado
    IF :new.FECHA_EXPIRACION < t_fecha_actual THEN
      -- Marcar la membresía como "Vencida"
      :new.ESTADO := 'Vencida';
    END IF;
  END Trg_Vencimiento_Membresia;

  -- Trigger para verificar la disponibilidad de espacios en una reserva
  CREATE OR REPLACE NONEDITIONABLE TRIGGER Trg_Verificar_Reserva
  BEFORE INSERT ON RESERVAS
  FOR EACH ROW
  DECLARE
    v_cupos_disponibles INT;
  BEGIN
    -- Obtener el número de espacios disponibles en la clase
    SELECT (CLASES.ESPACIOS - NVL(COUNT(*), 0))
    INTO v_cupos_disponibles
    FROM RESERVAS
    JOIN CLASES ON RESERVAS.ID_CLASE = CLASES.ID_CLASE
    WHERE RESERVAS.ID_CLASE = :new.ID_CLASE
    GROUP BY CLASES.ESPACIOS;

    -- Verificar si hay espacios disponibles
    IF v_cupos_disponibles <= 0 THEN
      --Cuando no hay espacios disponibles
      RAISE_APPLICATION_ERROR(-20001, 'No hay espacios disponibles en esta clase. La reserva ha sido rechazada.');
    END IF;
  END Trg_Verificar_Reserva;
END TriggersPackage;

EXEC TriggersPackage.Trg_Actualizar_Fecha_Ultimo_Mov;
EXEC TriggersPackage.Trg_Renovar_Membresia;
EXEC TriggersPackage.Trg_Vencimiento_Membresia;
EXEC TriggersPackage.Trg_Verificar_Reserva;
